config/routes.rb
Rails.application.routes.draw do
  resources :cocktails, only: [:index, :show, :new, :create] do
    resources :doses, only: [:new, :create]
  end
  resources :doses, only: [:destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_many :ingredients, :through => :doses
  validates :name, presence: true, uniqueness: true
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient
  validates :description, presence: true
  validates :cocktail, uniqueness: { scope: :ingredient }
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses
  validates :name, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  def index
    @cocktails = Cocktail.all
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to cocktail_path(@cocktail)
    else
      render new_cocktail_path
    end
  end

  def show
    @cocktail = Cocktail.find(params[:id])
    @dose = Dose.new
  end

  private

  def cocktail_params
    params.require(:cocktail).permit(:name)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController

  def new
    @dose = Dose.new
    @cocktail = Cocktail.find(params[:cocktail_id])
  end

  def create

    @dose = Dose.new(dose_params)
    @cocktail = Cocktail.find(params[:cocktail_id])

    @dose.cocktail = @cocktail
    if @dose.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  def destroy
    @dose = Dose.find(params[:id])
    @dose.destroy
    redirect_to cocktail_path(@dose.cocktail)
  end

  private

  def dose_params
    params.require(:dose).permit(:description, :ingredient_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/views/cocktails/index.html.erb
<div class="container">
<h1>Mister Cocktail</h1>

<ul>
  <% @cocktails.each do |cocktail| %>
  <li><%= link_to cocktail.name, cocktail_path(cocktail[:id]) %> </li>
  <% end %>
</ul>

<span><%= link_to "Add Cocktail", new_cocktail_path, class: "btn btn-success" %></span>

</div>

app/views/cocktails/new.html.erb
<div class="container">
<h2>Add a cocktail</h2>

<%= simple_form_for @cocktail do |f| %>
<%= f.input :name %>
<%= f.button :submit %>
<% end %>

<%= link_to "Go back", cocktails_path %>
</div>

app/views/cocktails/show.html.erb
<div class="container">
<h2><%= @cocktail.name %></h2>

<ul>
  <% @cocktail.doses.each do |dose| %>
  <li>
    <%= dose.description %> - <%= dose.ingredient.name %> -
    <%= link_to "Remove", dose_path(dose), method: :delete, data: { confirm: "Are you sure?" } %>
  </li>
  <% end %>
</ul>

<%= link_to "Add ingredient", new_cocktail_dose_path(@cocktail), class: "btn btn-success" %>
<br>
<%= link_to "Go back", cocktails_path, class: "btn btn-warning" %>
</div>

app/views/doses/new.html.erb
<div class="container">
<h3>Add ingredient</h3>
<%= simple_form_for [@cocktail, @dose] do |f| %>
  <%= f.input :description %>
  <%= f.association :ingredient %>
  <%= f.button :submit %>
<% end %>

<%= link_to "Go back", cocktail_path(@cocktail), class: "btn btn-primary" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>